### ISSUE TITLE
Recognize dproj as XML

### ISSUE THREAD

**Issue by viniciusfbb** [alefragnani/atom-language-pascal#35] opened 2021-12-22 13:07 UTC
It would be great if this package could add dproj recognition as XML. I currently change my config.cson of my atom by adding:

```cson
  core:
    customFileTypes:
      "text.xml": [
        "dproj"
      ]
```

I don't exactly know if the package would be able to do this recognition, but it would be a great feature.

**Comment by alefragnani** [comment] 2021-12-23 23:11
Hi @viniciusfbb ,

I don't remember seeing such setting on language package definition, and it's been a while I don't play with Atom API.

An alternative solution would be to try add more than one language at the same package. The downside of this solution would be to create a duplicate of XML grammar. 

You could try copying the grammar from XML package and add it to the extension (inside the `grammars` folder). 

Hope this helps

**Comment by alefragnani** [comment] 2022-08-13 15:38
Hi @viniciusfbb ,

Are you aware of the recent [archiving announcement](https://github.blog/2022-06-08-sunsetting-atom/) made by Atom’s team?

Since I’ve moved most of my development workflow and efforts to **VS Code**, where I also have developed a [Pascal extension](https://marketplace.visualstudio.com/items?itemName=alefragnani.pascal), I’ve decided to archive this repository in December as well.

So, I would like to know if you have intentions to create a PR for this feature (and #36 as well), otherwise, I would close both issues.

Thank you / Obrigado 😁

**Comment by viniciusfbb** [comment] 2022-08-13 15:51
Hi Alessandro!

Oh, it's such a shame that the Atom is being archived! I use it daily as a text editor in general. But in the face of the announcement, it does not justify any further development, it can close.

**Comment by alefragnani** [comment] 2022-08-13 16:10
Yeah, it’s really a shame. It was a great product and platform back then, but I’ve noticed its slowdown in development pace in recent years. It will be missed.

But fortunately, VS Code is a great alternative, delivering almost everything Atom does, and IMO, is faster and lighter. And as a Delphi developer, you will notice a few Delphi focused extensions [I’ve developed](https://marketplace.visualstudio.com/items?itemName=alefragnani.delphi-pack), which could make your life easier.

Thank you

**Closed by alefragnani** 2022-08-13 16:10 UTC
Labels: enhancement, good first issue
